### ISSUE TITLE
Mark what parts of the styleguide are relevant for add-ons (WebExtension)

### ISSUE THREAD

**Issue by designakt** [FirefoxUX/StyleGuide#1]

**Comment by pwalm** [comment]
On this! Great idea.

**Comment by pwalm** [comment]
@designakt You guys built a google doc with this content, right? Can you share the link?

**Comment by designakt** [comment]
I think you might be referring to this:
https://docs.google.com/document/d/1oJ89bxM6jLBYS1fC66VftB-2WGfadYruzxGk5jRcBAs/edit
Where we collect content on how to use certain elements we have specified.

or this:
https://docs.google.com/document/d/1KjwASXMhetMzvvIki0ZAT20Lw6zXbFSFLWGPN5oXnwE/edit#heading=h.xb67pmm5h40v
Where we collect all UI Elements relevant for WebExtensions (specified or not).

**Comment by bwinton** [comment]
Since [the add-ons page](http://firefoxux.github.io/StyleGuide/#/home/addons) is now a thing in the style guide, I think we can close this…
