### ISSUE TITLE
Pick a colour palette for code from Highlight.js

### ISSUE THREAD

**Issue by pwalm** [FirefoxUX/StyleGuide#10]
Currently browsing...
(this is also a test issue to check if Trello integration is working)

**Comment by pwalm** [comment]
https://highlightjs.org/static/demo/

**Comment by pwalm** [comment]
Let's go with "Color Brewer"
![screen shot 2016-01-05 at 10 58 42 am](https://cloud.githubusercontent.com/assets/6797635/12124634/585ad4f6-b39b-11e5-9254-1d6df3e697cc.png)

**Comment by bwinton** [comment]
[Already done](https://github.com/FirefoxUX/StyleGuide/blob/gh-pages/src/components/Editor.jsx#L6)!  :wink:
