### ISSUE TITLE
Make sure all components have a home

### ISSUE THREAD

**Issue by pwalm** [FirefoxUX/StyleGuide#19]
Scour the style guide files and makes sure everything is represented on the style guide site.

**Comment by pwalm** [comment]
This is everything from the master Sketch file. The only major change is that I'm going to move buttons/checkboxes/radio buttons under a section called "Controls".

![fullsizerender](https://cloud.githubusercontent.com/assets/6797635/12130335/7280b2c4-b3be-11e5-9e15-f4d15b605a6b.jpg)

**Comment by pwalm** [comment]
Oh, add Panels at the bottom of Components

**Comment by pwalm** [comment]
CHANGE: Moving **Glyphs** to Components, it makes more sense there.

**Comment by pwalm** [comment]
**Controls** layout
![img_5711](https://cloud.githubusercontent.com/assets/6797635/12157988/daed6eca-b48a-11e5-9571-582ab6045d15.JPG)

**Comment by bwinton** [comment]
Just to double-check, only the things at the first level will be pages?
(So, Typography is a page containing Labels, and Labels isn't its own page…)

**Comment by pwalm** [comment]
You are correct!

**Comment by bwinton** [comment]
And I think this closes the issue.  🙂
