### ISSUE TITLE
Sticky header

### ISSUE THREAD

**Issue by pwalm** [FirefoxUX/StyleGuide#23]
Is this something we can fit into v1?

**Comment by pwalm** [comment]
![screen shot 2016-01-05 at 3 24 20 pm](https://cloud.githubusercontent.com/assets/6797635/12130584/72a4c1ee-b3c0-11e5-8cf1-a22a2ef0999b.png)

**Comment by bwinton** [comment]
I think so…

**Comment by pwalm** [comment]
:+1:

**Comment by bwinton** [comment]
Can I get (svg) graphics for the up and down arrows, @pwalm?  (And then re-assign it to me when they're attached, and I'll finish this off.  :smiley:

**Comment by pwalm** [comment]
Added! Check the **site-controls** folder

**Comment by bwinton** [comment]
Updated in 6316f2673fc6ebd061f3298def9fb88ea8852f38
