### ISSUE TITLE
Page Layout Spacing

### ISSUE THREAD

**Issue by pwalm** [FirefoxUX/StyleGuide#25]
How to space groups of elements on pages where there are different kinds of controls.
![screen shot 2016-01-07 at 1 57 46 pm](https://cloud.githubusercontent.com/assets/6797635/12184027/9a8c5748-b547-11e5-89d9-2265d3d7c1fd.png)

**Comment by bwinton** [comment]
I believe this was fixed by e153c98ea55dd2249127c393be32be8c697b8aef
