### ISSUE TITLE
Overlay colour swatch on hover to indicate we'll copy it.

### ISSUE THREAD

**Issue by bwinton** [FirefoxUX/StyleGuide#27]

**Comment by bwinton** [comment]
Check out http://dongerlist.com/ in Firefox Release.

**Comment by pwalm** [comment]
This little guy:
╰(◕ᗜ◕)╯

**Comment by pwalm** [comment]
What if instead of the "copy" slide down, the hex value fades out and "click to copy" fades in, centered to the colour block

**Comment by bwinton** [comment]
Hmmm…  I would worry that then you wouldn't be able to see the colour you were copying.  What's the problem with the sliding down?  Would it be better if it was the same, but with a fade in instead?

**Comment by pwalm** [comment]
How bout this:
![screen shot 2016-01-22 at 12 54 53 pm](https://cloud.githubusercontent.com/assets/6797635/12522768/601a2f38-c107-11e5-877e-a3e6e2924bc6.png)
