### ISSUE TITLE
Menu Fine Tuning

### ISSUE THREAD

**Issue by epang** [FirefoxUX/StyleGuide#32]
Hey @bwinton here are some changes we'll need for the menu, let me know if you have any questions. Once these are done I'll take another look :). Thanks!
- [x] Motion of Menu (including the underlay movement) - https://www.dropbox.com/s/a94shyb943mtrzy/style_guide_nav.mp4?dl=0
- [x] Vertical Spacing - for main Categories (Overview, Design Foundation, etc.) the spacing should be 60px from base line to base line
- [x] Vertical Spacing - from main category to sub category - 40px from base line to base line
- [x] Font Weights - Can we drop the weight of the main categories (but 1 weight), they are looking a little heavy
- [x] Arrows - they are 7 pixel wide (up for closed and down for open).  Do I need to provide an asset for these or can these be created in css?
- [x] Hover state of main categories - on mouse over the text should change to #505050
- [x] Hover state of selected sub categories - none needed (currently they turn to a lighter blue but we can remove this since clicking the section again doesn't do anything)
- [x] Sub menu items shouldn't shift up and down when selected

**Comment by bwinton** [comment]
- Yeah, I forgot that I didn't do the motion yet…  Sorry about that!
- I think an SVG for the arrows would be the easiest…
- I'm not sure what you mean by “Sub menu items should shift up and down when selected”.  Could you expand that point a little more?
- We can drop the weight of the main categories from `400` to `300`, which looks like this:<br>
  <img width="296" alt="screenshot 2016-07-07 09 33 41" src="https://cloud.githubusercontent.com/assets/159571/16654920/fc7aaef6-4425-11e6-998e-df40a9cacc07.png"><br>
  (That seems a little light to me, though.)  More font-weight details [here](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight)

Thanks!  😃

**Comment by epang** [comment]
no problem!  I'll get a svg of the arrow ready.
Sorry typo - should have been "Sub menu items should**n't** shift up and down when selected.  Right now move a little when clicked.

**Comment by bwinton** [comment]
(Cool.  I edited the first comment to reflect that.  😄)

**Comment by epang** [comment]
Thanks Blake!  For some reason I didn't see the font weight part till now.  I agree, they end up blending in too much.  Let's leave as is (and thanks for the link!).

**Comment by epang** [comment]
I've added the svg for the arrow here: https://www.dropbox.com/sh/jng01hh6kqwwd23/AACEZ-Prh8G7v7HaZqWU73KFa?dl=0

Thanks!

**Comment by bwinton** [comment]
So, currently we have introductory content for each top level item (like [this](http://firefoxux.github.io/StyleGuide/#/home)).  Are you thinking that clicking on the top level would just expand/collapse that section, and not change the displayed content?  (That seems like reasonable thing to do, but I wanted to check with you first. 🙂)

**Comment by epang** [comment]
Yep, that's the idea.  So the content should only change when a sub header is pressed.  Thanks for checking :)

**Comment by bwinton** [comment]
I think this is basically done.  🙂
