### ISSUE TITLE
Indication & Feedback for copying a color when clicking it

### ISSUE THREAD

**Issue by designakt** [FirefoxUX/StyleGuide#4]
How does the user know that they can copy the color, and how would the know that the color is now in their clipboard? And would they now it the color contains the # or not? Even if indication is only via the tooltip, giving feedback seams very important to me.
For examples on how such indication and feedback could work see bit.ly shortened link or dropbox & google drive link sharing.

**Comment by shorlander** [comment]
Could overlay "Copy to Clipboard" on hover? And some kind of confirmation overlay when it happens?

**Comment by bwinton** [comment]
Hey, I think I fixed this at ca9f77d2!  :grinning:
