### ISSUE TITLE
Shades appear to have been repeated for the blue colour

### ISSUE THREAD

**Issue by FatOrangutan** [FirefoxUX/StyleGuide#41]
At line numbers 69, 70, and 71 over here -> https://github.com/FirefoxUX/StyleGuide/blob/master/contents/colours.html#L69 - they are all #2284e6. Is this intentional?

Apologies if this isn't the right place to ask this.

**Comment by bwinton** [comment]
This is the totally the right place to ask.  @shorlander, @epang: Was this a typo?

**Comment by epang** [comment]
@bwinton typo, i've put in a pull request with the fix. Thanks!

**Comment by bwinton** [comment]
Fixed by #42.  Thanks for the bug report!
