### ISSUE TITLE
Site logo and title link to "Hello there" page

### ISSUE THREAD

**Issue by ryanfeeley** [FirefoxUX/StyleGuide#44]
STEPS TO REPRODUCE

1. Visit https://bwinton.github.io/StyleGuide/
2. Click Firefox UX link in top left

EXPECTED RESULTS

* It directs to the home page of the style guide: https://bwinton.github.io/StyleGuide/#/welcome

ACTUAL RESULTS

* It goes to this WIP page https://firefoxux.github.io/

**Comment by bwinton** [comment]
I think it's going to the right place, but we should probably fill out that page.
Filed as FirefoxUX/firefoxUX.github.io#1.
