### ISSUE TITLE
I think you'll find COLOUR is not a word

### ISSUE THREAD

**Issue by johngruen** [FirefoxUX/StyleGuide#5]

**Comment by helenvholmes** [comment]
:joy:

**Comment by pwalm** [comment]
it is ON, yankee

**Comment by bwinton** [comment]
In the time-honoured tradition of Mozilla, let the best gif win!

**Comment by pwalm** [comment]
![giphy](https://cloud.githubusercontent.com/assets/6797635/11985652/e537478a-a97b-11e5-9427-de1aea60c5ad.gif)

**Comment by helenvholmes** [comment]
![party-hard](https://cloud.githubusercontent.com/assets/1720093/11987910/59744b14-a9b5-11e5-84ec-dcbad59c6b74.gif)
Is there like a method for determining such gif quality

**Comment by bwinton** [comment]
As an impartial, unbiased third party, I will naturally choose the best gif according to my tastes.  :wink:
