### ISSUE TITLE
Link at top of old style guide is dead

### ISSUE THREAD

**Issue by sevaan** [FirefoxUX/StyleGuide#57]
The link to the "Staging Site" at the top of the old Style Guide is dead and should probably redirect to the correct place.

http://design.firefox.com/StyleGuide/

**Comment by aminalhazwani** [comment]
@bwinton I pushed an update 7321800 but it did not run the build, any idea? Thank you @sevaan for reporting this!

**Comment by bwinton** [comment]
Yeah, we turned the builds off because no-one should be using this repo anymore…  :)
I'll kick off a manual build.

**Comment by bwinton** [comment]
Fixed.
